version: 2
updates:
  - package-ecosystem: pip
    directory: /mote-kernel
    schedule:
      interval: weekly
    groups:
      kernel-development-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
