version: 2
updates:
  - package-ecosystem: pip
    directory: /mote-kernel
    schedule:
      interval: weekly
    groups:
      kernel-development-dependencies:
        dependency-type: development
  - package-ecosystem: cargo
    directory: /mote-infra/persistence/local
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /mote-infra/persistence/cloudflare/python
    schedule:
      interval: weekly
    groups:
      persistence-cloudflare-python-development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /mote-infra/persistence/cloudflare/ts
    schedule:
      interval: weekly
    groups:
      persistence-cloudflare-typescript-development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /mote-container/cloudflare/ts
    schedule:
      interval: weekly
    groups:
      container-cloudflare-typescript-development-dependencies:
        dependency-type: development
  - package-ecosystem: pip
    directory: /mote-container/cloudflare/python
    schedule:
      interval: weekly
    groups:
      container-cloudflare-python-development-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /mote-container/cloudflare/python
    schedule:
      interval: weekly
    groups:
      container-cloudflare-python-wrangler:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
