/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: ff8e0611880ea64dca0e451e6cbb7ea9)
interface __BaseEnv_Env {
	AGENT_OBJECTS: DurableObjectNamespace<import("./index").AgentDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgentDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
