/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.jsonc --include-runtime=false tests/worker-configuration.d.ts` (hash: b039d10f2997ca1b5549ede0dacdbdd7)
interface __BaseEnv_Env {
    PERSISTENCE_TEST_OBJECTS: DurableObjectNamespace<
        import('./worker').PersistenceTestDurableObject
    >
}
declare namespace Cloudflare {
    interface GlobalProps {
        mainModule: typeof import('./worker')
        durableNamespaces: 'PersistenceTestDurableObject'
    }
    interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
